version: '3.7'

services:
    locationservice:
        build:
            context: ./
            dockerfile: PaymentGateway/Dockerfile
        ports:
            - 5000:5000
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_URLS=http://+:5000