version: '3.7'

services:
    paymentgateway:
        build:
            context: ./
            dockerfile: PaymentGateway/Dockerfile
        ports:
            - 5000:5000
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_URLS=http://+:5000
        depends_on:
            - mongodb
        networks:
            - local-network
    mongodb:
        image: mongo
        restart: always
        environment:
            - MONGO_INITDB_DATABASE=paymentGatewayDb
            - MONGO_INITDB_ROOT_USERNAME=admin
            - MONGO_INITDB_ROOT_PASSWORD=pass12345
        ports:
            - 27017:27017
        networks:
            - local-network
    mongo-express:
        image: mongo-express
        restart: "on-failure"
        depends_on:
            - mongodb
        environment:
            - ME_CONFIG_OPTIONS_EDITORTHEME=ambiance
            - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
            - ME_CONFIG_BASICAUTH_USERNAME=dev
            - ME_CONFIG_BASICAUTH_PASSWORD=devpassword
            - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
            - ME_CONFIG_MONGODB_ADMINPASSWORD=pass12345
            - ME_CONFIG_MONGODB_PORT=27017
            - ME_CONFIG_MONGODB_SERVER=host.docker.internal
        ports:
            - "8081:8081"
        networks:
            - local-network
networks:
  local-network:
    driver: bridge